; ========================================================================
; =================      ETEC Aristóteles Ferreira.     ==================
; ========          Yhan Christian Souza Silva         ===================
; =====   Programa_02  progsenha2.asm  ver. 0.2 data: 01/06/13.   =========                          
; ========================================================================


;Fazer um programa para acionar uma fechadura eletrônica
;Deverá possuir:
;Senha de 9 digitos qualquer
;Display para contar o número de teclas pressionadas
; * Limpa todos os digitos e volta para inicio
; # Para confirmação ENTER
;Digitar os 6 números depois digitar ENTER
;Se correta libera a fechadura
;Se incorreta toca o BUZZER
; para calar o BUZZER pressionar e soltar # 3 vezes



		ORG 0000H		;INICIO DE PROGRAMA
INICIO:		MOV SP,#60H		;DEFINO O INICIO DE UTILIZAÇÃO REGISTRADORES "LABEL"
		MOV R0,#30H	  	;MOVO O DADO 30H PARA R0
		MOV P0,#0FFH		;MOVO O DADO FF PARA P0
		MOV P1,#00H 		;LIMPO P1
		MOV A,#00H		;LIMPO ACC
		LCALL TEMPO		;SUB-ROTINA DE TEMPO
;-------------------------------------------------------------------------
		;EQUIVALENCIAS
				
             LIN_0 EQU P2.0		;LINHA 1 EQUIVALE A P2.0
             LIN_1 EQU P2.1		;LINHA 2 EQUIVALE A P2.1
             LIN_2 EQU P2.2		;LINHA 3 EQUIVALE A P2.2
             LIN_3 EQU P2.3 		;LINHA 4 EQUIVALE A P2.3
             
             COL_3 EQU P2.4     	;COLUNA 0 EQUIVALE A P2.4	
             COL_2 EQU P2.5		;COLUNA 1 EQUIVALE A P2.5
             COL_1 EQU P2.6		;COLUNA 2 EQUIVALE A P2.6
             COL_0 EQU P2.7     	;COLUNA 3 EQUIVALE A P2.7
	
		SJMP COLUNA0
;--------------------------------------------------------------------------
		;VARREDURA TECLADO
		
COLUNA0: 	CLR COL_0		;LIMPO COLUNA 0	
		JB LIN_0,S1		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		
		MOV A,#01H		;MOVO PARA A 01H
		LCALL D1		;CHAMO SUB-ROTINA D1
		LCALL TEMPO1		;SUB-ROTINA  TEMPO1
		
S1:		JB LIN_1,S2		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		MOV A,#04H		;MOVO PARA A 04H
		LCALL D1		;CHAMO SUB-ROTINA D1 
		LCALL TEMPO1		;SUB-ROTINA TEMPO1

S2:		JB LIN_2,S3		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE	
		MOV A,#07H		;MOVO PARA A 07H
		LCALL D1		;CHAMO SUB-ROTINA D1
		LCALL TEMPO1		;SUB-ROTINA TEMPO1
		
S3:		JB LIN_3,S4		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		LCALL TEMPO1		;SUB-ROTINA TEMPO1
		SETB COL_0		;SETO COLUNA 0
		LJMP LIMPA		;SALTO PARA ROTINA LIMPA
		
S4:		SETB COL_0		;SETO COLUNA 0
		LCALL TEMPO1		;SUB-ROTINA TEMPO1

COLUNA1: 	CLR COL_1		;LIMPO COLUNA 1
		JB LIN_0,S5		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		MOV A,#02H		;MOVO PARA A 02H
		LCALL D1		;CHAMO SUB-ROTINA D1
		LCALL TEMPO1		;SUB-ROTINA TEMPO1
		
S5:		JB LIN_1,S6		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		MOV A,#05H		;MOVO PARA A 05H
		LCALL D1		;CHAMO SUB-ROTINA D1
		LCALL TEMPO1		;SUB-ROTINA TEMPO1

S6:		JB LIN_2,S7		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE	
		MOV A,#08H		;MOVO PARA A 08H
		LCALL D1		;CHAMO SUB-ROTINA D1
		LCALL TEMPO1		;SUB-ROTINA TEMPO1

S7:		JB LIN_3,S8		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE	
		MOV A,#00H		;MOVO PARA A 00H
		LCALL D1		;CHAMO SUB-ROTINA D1
		LCALL TEMPO1		;SUB-ROTINA TEMPO1
S8:		SETB COL_1		;SETO COLUNA 1
				
COLUNA2: 	CLR COL_2		;LIMPO COLUNA 2
		JB LIN_0,S9		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		MOV A,#03H		;MOVO PARA A 03H
		LCALL D1		;CHAMO SUB-ROTINA D1
		LCALL TEMPO1		;SUB-ROTINA TEMPO1
		
S9:		JB LIN_1,S10		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		MOV A,#06H		;MOVO PARA A 06H
		LCALL D1		;CHAMO SUB-ROTINA D1
		LCALL TEMPO1		;SUB-ROTINA TEMPO1
		
S10:		JB LIN_2,S11		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		MOV A,#09H		;MOVO PARA A 09H
		LCALL D1		;CHAMO SUB-ROTINA D1
		LCALL TEMPO1		;SUB-ROTINA TEMPO1
		
S11:		JB LIN_3,S12		;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		LJMP ENTER		;PULO PARA ROTINA ENTER
				
S12:		SETB COL_2		;SETO COLUNA 2
		LJMP COLUNA0		;SALTO PARA COLUNA 0

;--------------------------------------------------------------------
		;ROTINA ENTER

ENTER:		CLR COL_2			;LIMPO COLUNA 2
		LCALL TEMPO			;SUB-ROTINA TEMPO
		JB LIN_3,ENTRA1			;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		LCALL TEMPO			;SUB-ROTINA TEMPO
		LJMP COMPARA			;SALTO PARA COMPARA
		
ENTRA1:		SETB COL_2			;SETO COLUNA 2
		LCALL TEMPO			;SUB-ROTINA TEMPO
		SJMP LIMPA			;SALTO PARA LIMPA
		
LIMPA:		CLR COL_0			;LIMPO COLUNA 0
		LCALL TEMPO			;SUB-ROTINA DE TEMPO
		JB LIN_3,LIMPA1			;VERIFICO O ACIONAMENTO DO BOTÃO/PULO PARA O SEGUINTE
		LCALL TEMPO			;SUB-ROTINA TEMPO
		LJMP INICIO			;SALTO PARA INICIO
				
LIMPA1:		SETB COL_0			;SETO COLUNA 0
		LCALL TEMPO			;SUB-ROTINA TEMPO
		SJMP ENTER			;PULO PARA ENTER

		 		
;---------------------------------------------------------		
	;COMPARAR SENHA

COMPARA:	MOV R0,#30H			;MOVO PARA R0 30H
		MOV A,#0			;MOVO PARA A 0
		LCALL TEMPO			;SUB-ROTINA TEMPO
		CJNE @R0,#1,ERRO		;COMPARO O DADO APONTADO COM R0, PULO PARA ERRO
		INC R0				;INCREMENTO R0
		LCALL TEMPO			;SUB-ROTINA TEMPO
		CJNE @R0,#4,ERRO		;COMPARO O DADO APONTADO COM R0, PULO PARA ERRO
		INC R0				;INCREMENTO R0
		LCALL TEMPO			;SUB-ROTINA TEMPO
		CJNE @R0,#7,ERRO		;COMPARO O DADO APONTADO COM R0, PULO PARA ERRO
		INC R0				;INCREMENTO R0
		LCALL TEMPO			;SUB-ROTINA TEMPO
		CJNE @R0,#2,ERRO		;COMPARO O DADO APONTADO COM R0, PULO PARA ERRO
		INC R0				;INCREMENTO R0
		LCALL TEMPO			;SUB-ROTINA TEMPO
		CJNE @R0,#5,ERRO		;COMPARO O DADO APONTADO COM R0, PULO PARA ERRO
		INC R0				;INCREMENTO R0
		LCALL TEMPO			;SUB-ROTINA TEMPO
		CJNE @R0,#6,ERRO		;COMPARO O DADO APONTADO COM R0, PULO PARA ERRO
		MOV A,#1			;MOVO PARA A 1
		MOV P0,A			;MOVO O DADO DE A PARA P0
		CLR COL_0			;LIMPO COLUNA 0
		LCALL TEMPO			;SUB-ROTINA TEMPO	
		JB LIN_3, $			;VERIFICO LINHA 3, TRAVO AQUI
		LJMP INICIO			;SALTO PARA INICIO	
		
ERRO:		CLR P3.7			;ACIONA BUZZER	
		LCALL TEMPO			;SUB-ROTINA TEMPO	
		CLR COL_0			;LIMPO COLUNA 0
		LCALL TEMPO			;SUB-ROTINA TEMPO
		JB LIN_3,$			;VERIFICO LINHA 3, TRAVO AQUI
		LCALL TEMPO			;SUB-ROTINA TEMPO
		JB LIN_3,$			;VERIFICO LINHA 3, TRAVO AQUI
		LCALL TEMPO			;SUB-ROTINA TEMPO
		JB LIN_3,$			;VERIFICO LINHA 3, TRAVO AQUI
		LCALL TEMPO			;SUB-ROTINA TEMPO	
		SETB COL_0			;SETO COLUNA 0
		LCALL TEMPO			;SUB-ROTINA TEMPO
		SETB P3.7			;SETO P3.7, CALO O BUZZER
		LJMP INICIO			;SALTO PARA INICIO

;--------------------------------------------------------------------------
		;COLOCA A SENHA EM R0 PARA DEPOIS COMPARAR

D1:		MOV @R0,A		;MOVO O DADO DE A PARA O REGISTRADOR APONTADO POR R0
		LCALL TEMPO		;SUB-ROTINA TEMPO
		INC R0			;INCREMENTO R0
		LCALL TEMPO		;SUB-ROTINA TEMPO
		INC P1			;INCREMENTO P1
		LCALL TEMPO		;SUB-ROTINA TEMPO
		CJNE R0,#36H,PULA	;COMPARO O DADO APONTADO COM R0, PULO PARA "PULA"
		LJMP ENTER		;PULOPARA ENTER
PULA:		LCALL TEMPO		;SUB-ROTINA TEMPO	
		RET			;VOLTA PARA DIGITO APERTADO MAIS 1
												
;--------------------------------------------------------------------------
		; SUBROTINA DE TEMPO
       
TEMPO:	MOV R1,#2			;R0=2        10 MILISEGUNDOS
VOLTA2:	MOV R2,#50			;R1=50
VOLTA1: MOV R3,#50			;R2=50
	DJNZ R3,$			;FICA DECREMENTANDO R1 ATE QUE ELE SEJA = 0
	DJNZ R2,VOLTA1			;FICA DECREMENTANDO R2 ATE QUE ELE SEJA = 0
	DJNZ R1,VOLTA2			;FICA DECREMENTANDO R0 ATE QUE ELE SEJA = 0
	RET				;VOLTA PARA LCALL MAIS UM
	
       
TEMPO1:	MOV R4,#2			;R4=2        10 MILISEGUNDOS
VOLTA22:MOV R5,#50			;R5=50
VOLTA11:MOV R6,#50			;R6=50
	DJNZ R6,$			;FICA DECREMENTANDO R1 ATE QUE ELE SEJA = 0
	DJNZ R5,VOLTA11			;FICA DECREMENTANDO R2 ATE QUE ELE SEJA = 0
	DJNZ R4,VOLTA22			;FICA DECREMENTANDO R0 ATE QUE ELE SEJA = 0
	RET				;VOLTA PARA LCALL MAIS UM	
	
	END				;FIM DE PROGRAMA